server {

    listen 443 ssl;

    server_name jejaktanahku.raflihaidar.my.id;


    ssl_certificate /etc/letsencrypt/live/app.raflihaidar.my.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.raflihaidar.my.id/privkey.pem;


    location / {

        proxy_pass http://jejaktanahku-app:80;

        proxy_set_header Host $host;

    }


    location /api/ {

        proxy_pass http://jejaktanahku-be:5000;

        proxy_set_header Host $host;

    }
}